obj-$(CONFIG_MTK_USBFSH) := musbfsh_core.o musbfsh_mt65xx.o musbfsh_debugfs.o

ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb20
ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb11
ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb11/$(CONFIG_MTK_PLATFORM)/
ccflags-y += -I$(srctree)/include/linux/

